#include "test.h"

#include "engine/manager.c"

// From: bin/ls manager-test.c | grep -v 'engine/manager-test.c' | xargs grep -h '#include' | grep -v test.h | sort -u
#include "camera/camera.c"
#include "camera/manager.c"
#include "gpu/manager.c"
#include "gpu/view-mock.c"
#include "log/manager-mock.c"
#include "math/fnv.c"
#include "math/quad.c"
#include "os/clock-mock.c"
#include "render/layout.c"
#include "render/manager.c"
#include "render/vector.c"
#include "resource/manager.c"
#include "resource/pointer-allocator.c"
#include "resource/resource.c"
#include "string/id-table.c"
#include "string/id.c"
#include "string/manager.c"
#include "world/grid.c"
#include "world/manager.c"
#include "world/vector.c"
